/**
 * 14 Boss 分配模板与减伤轴事件。
 * 占位符由引擎替换：{mt}{ot}{h1}{h2}{h3}{melee}{ranged}{cloak}{trap}{interrupt}{immune}
 * {dr1}{dr2}{dr3}{heal1}{heal2}{heal3} = 点名后的减抬简称
 */
window.SOO_PLANNER_BOSSES = [
  {
    id: "immerseus",
    idx: 1,
    name: "伊墨苏斯",
    lust: "开场",
    flex: { heal: true },
    pull: "半场就位 → 副T起手吃一层冲击后主T换嘲 → 肿胀规则/平移 → 嗜血开场",
    assignTpl: [
      "【P1 坦】{ot} 起手抗 Boss 吃 1 层腐蚀冲击 → {mt} 换嘲后一直抗、把头带好（起手不抗）",
      "【P1 坦】{ot} 换嘲后拉凝结煞",
      "【奶】{h1} 主加双坦；{h2} 加团（肿胀驱散，尽量 3～4 层驱）",
      "【弹性奶】本战打 3 奶：{h3} 切奶萨（链接/潮汐）；P2 可三角分边奶白软",
      "【DPS】整体平移躲脚下圈；近战贴身后（普攻不叠肿胀），远程竖线",
      "【肿胀】约 4 层停手/等驱；{cloak} 超 4 层再开免疫续消（非起手开）",
      "【旋涡】能穿往右穿；旋涡期间无黑水，近战可 AE；尽量第二次肿胀前进 P2",
      "【P2】{ot} 开减伤踩水圈；打黑软远程打远近战打近；{trap} 减速陷阱预铺；没血吃糖",
      "【P2 奶】{h1}/{h2}/{h3} 分扇区奶白软（有第三奶更稳）",
    ],
    cdEvents: [
      { when: "旋涡硬顶", prefer: ["shell", "barrier", "aura", "rally"], note: "能穿则穿" },
      { when: "狂暴末轮踩池", prefer: ["barrier", "aura", "link", "rally"], note: "对齐硬顶" },
      { when: "冲击第二下", prefer: ["ps", "sac"], note: "优先换坦；外置保坦" },
    ],
  },
  {
    id: "protectors",
    idx: 2,
    name: "堕落的守护者",
    lust: "开场",
    flex: { heal: true },
    pull: "绝命序洛克→何→孙 → 印记链 + 灾祸减抬表 → 嗜血开场",
    assignTpl: [
      "【坦】{mt} 坦洛克（锥形背离）；{ot} 坦何（凿击背对）",
      "【绝命】洛克：{mt} 接阴郁；{ot} 何+悲苦外拉；何绝命印记链（冰箱优先，勿传坦）",
      "【孙绝命】全员进罩；远程罩外大体，近战罩内小怪",
      "【奶】{h1} 盯双坦；{h2} 祸驱 + 灾祸/炼狱团减抬",
      "【弹性奶】有 {h3} 时：{h3} 专管链接/潮汐顶灾祸递增",
      "【打断】{interrupt} 轮断灼烧/阴郁震击",
      "【斩杀】约 15 秒三线同步",
    ],
    cdEvents: [
      { when: "灾祸①", prefer: ["barrier", "shell", "aura"] },
      { when: "灾祸②", prefer: ["aura", "link", "tide", "kings"] },
      { when: "炼狱分摊", prefer: ["barrier", "shell"], note: "或留给孙罩" },
      { when: "后续灾祸", prefer: ["demo", "rally", "barrier"], note: "递增后更吃表" },
    ],
  },
  {
    id: "norushen",
    idx: 3,
    name: "诺鲁什",
    lust: "约 50%（DPS 基本 0 腐蚀后）",
    pull: "报试炼波次 + 虚空分配 → 50% 前完成计划 → 开打",
    assignTpl: [
      "【试炼】波1 {mt}+{h1}+2DPS；波2 {ot}+{h2}+2DPS；波3 双坦+剩余 DPS（可微调）",
      "【场上】怀疑换坦；盲仇躲 Boss 背后；虚空优先当前坦/指定治疗踩",
      "【大怪】同波两人错开击杀，避免双强化",
      "【奶】场上保覆盖；试炼内跟自己波",
    ],
    cdEvents: [
      { when: "大怪在场团压", prefer: ["shell", "tide", "kings", "hymn"] },
      { when: "冰寒恐惧高峰", prefer: ["barrier", "aura", "link", "rally"] },
    ],
  },
  {
    id: "pride",
    idx: 4,
    name: "傲之煞",
    lust: "30% 释放",
    pull: "Boss 朝诺鲁什 + 标定监狱/赐福点 → 背迷宫 → 开打",
    assignTpl: [
      "【坦】{mt}/{ot} 受伤傲慢立刻换；监狱协助对角踩板",
      "【奶】{h1} 盯坦；{h2} 赐福窗驱印记 + 肿胀减抬",
      "【裂隙】远程轮班关；最佳窗≈肿胀AE后25秒；{mt} 冲锋/跳跃可一次多关",
      "【监狱】两人组踩板；【放逐】外场秒碎片",
      "【具现】{interrupt} 断嘲讽冲击",
      "【肿胀前】全员报傲慢档；30%后可放弃关隙专心输出",
    ],
    cdEvents: [
      { when: "肿胀①", prefer: ["barrier", "shell"] },
      { when: "肿胀②", prefer: ["aura", "link", "tide", "kings"] },
      { when: "肿胀③", prefer: ["demo", "rally", "hymn", "tranq"] },
      { when: "30% 释放", prefer: ["barrier", "aura", "rally", "tide"], note: "嗜血同步" },
    ],
  },
  {
    id: "galakras",
    idx: 5,
    name: "迦拉卡斯",
    lust: "P2 落地",
    flex: { tank: true },
    pull: "找洛瑟玛 → 确认塔队/步兵专人 → 木栏间就位",
    assignTpl: [
      "【地面】{mt} 拉怪木栏间；{h2} 地面奶",
      "【塔队】{ot}+{h1}+2~3DPS；清左后 {ot} 坐左炮",
      "【弹性坦】有 {t3} 时：{t3} 切防上塔/{ot} 可留守地面",
      "【步兵】{trap} 猎人专人秒塔楼步兵",
      "【优先】碎骨晕骨折 > 萨满断链/拆图腾 > 拆旗",
      "【P2】两营分摊火球；每营有奶；约 3 层换坦",
    ],
    cdEvents: [
      { when: "P2 递加团伤", prefer: ["barrier", "shell", "aura", "tide", "kings", "rally"] },
      { when: "骨折漏控", prefer: ["ps", "sac", "kings"], note: "外置保人" },
    ],
  },
  {
    id: "juggernaut",
    idx: 6,
    name: "钢铁战蝎",
    lust: "突击开场",
    flex: { heal: true },
    pull: "突击禁正面 → 副T点雷 + 攻城三次减抬 → 嗜血开场",
    assignTpl: [
      "【突击】{mt} 主抗禁正面；{ot} 点雷 + 灼燃约 3 层换坦",
      "【站位】近战身后；远程略散；躲钻头/炮弹/锯刃",
      "【激光】点名带离沥青",
      "【攻城】集合吃击退远离；10H 可远离少打保命",
      "【弹性奶】有 {h3} 时：三次攻城震荡波用链接/潮汐穿插 1/2/3 减抬",
    ],
    cdEvents: [
      { when: "攻城震荡波①", prefer: ["barrier", "shell"] },
      { when: "攻城震荡波②", prefer: ["aura", "link", "tide"] },
      { when: "攻城震荡波③", prefer: ["demo", "rally", "kings", "hymn"] },
    ],
  },
  {
    id: "shaman",
    idx: 7,
    name: "库卡隆黑暗萨满",
    lust: "约 25%",
    flex: { tank: true },
    pull: "标定两组 → 清狼 → 85% 前分边 → 铁监牢盾",
    assignTpl: [
      "【开场】清狼；85% 前分边（共享血）",
      "【弹性坦】本战打 3T：{t3} 切防骑",
      "【卡组·远程】{mt}+{h1}+远程组 打卡德里斯（单坦+铁监牢外置/压制）",
      "【哈组·近战】{ot}+{t3}+{h2}+近战组 打哈洛姆（双坦换层约 5～6）",
      "【卡】铁监牢满血盾；风暴躲建筑",
      "【哈】铁墓坡沿；洪流站定；墙来下坡",
    ],
    cdEvents: [
      { when: "铁监牢", prefer: ["ps", "sac", "ironbark", "cocoon"], note: "外置+坦减" },
      { when: "坠落灰烬", prefer: ["barrier", "aura", "link", "rally"] },
      { when: "毒雾/洪流", prefer: ["shell", "tide", "kings"] },
    ],
  },
  {
    id: "nazgrim",
    idx: 8,
    name: "纳兹戈林将军",
    lust: "<10% 清波后",
    flex: { tank: true },
    pull: "防御停手纪律 + 小怪优先级 → Boss 靠刷新侧",
    assignTpl: [
      "【坦】{mt} 主抗靠刷新侧；{ot} 接小怪/斩杀风筝",
      "【优先】旗 > 萨满(拉远) > 法师 > 盗贼 > 战士 > 狙击；猎人小怪只盯奶",
      "【弹性坦】有 {t3} 时：{t3} 专风筝斩杀/<10% 小怪，{ot} 可协坦；开场可 2-2-2 换嘲减怒",
      "【跳跃】可专人靠近诱导落点",
      "【姿态】防御=全团停手；战斗/狂暴听指挥",
      "【<10%】清当前波 → {ot}/{t3} 风筝全小怪 → 嗜血只打 Boss",
    ],
    cdEvents: [
      { when: "斩杀", prefer: ["ps", "sac"], note: "坦自保+外置" },
      { when: "战歌", prefer: ["barrier", "shell", "aura", "link"] },
      { when: "破坏者", prefer: ["demo", "rally"], note: "风筝远离" },
      { when: "斩杀阶段团压", prefer: ["tide", "kings", "rally", "hymn"] },
    ],
  },
  {
    id: "malkorok",
    idx: 9,
    name: "马尔考罗克",
    lust: "开场",
    flex: { heal: true },
    pull: "P1 按盾/外壳思维 → 内爆必踩/吐息必出 → 嗜血开场",
    assignTpl: [
      "【P1】{mt}/{ot} 换坦；弧形斩后全体出吐息；内爆虚空有人踩",
      "【P1 奶】优先 {heal1} 外壳/吸收盾思维；非纯直疗",
      "【弹性奶】有 {h3} 时：{h3} 链接/潮汐补第三轮起团压",
      "【白球】无视吸收盾直接破盾——平时勿碰；第一次吐息后 {immune}/{cloak} 清一轮",
      "【软泥】8码减速圈；近战闪技能时离开，坦可临时带开",
      "【P2】优先 {ot}（酒仙/熊）独坦血怒；速驱错位；定身用自由/风行；可清场撞球",
      "【轮次】每轮 P2 后 +25% 伤；第二次P1隔次减伤；第三轮起减抬加码",
    ],
    cdEvents: [
      { when: "P1 常态铺盾", prefer: ["shell", "barrier"] },
      { when: "第三轮起 P1", prefer: ["barrier", "aura", "link", "shell", "tide"] },
      { when: "P2 独坦危急", prefer: ["ps", "sac", "ironbark"] },
    ],
  },
  {
    id: "spoils",
    idx: 10,
    name: "潘达利亚战利品",
    lust: "—",
    flex: { heal: true, tank: true },
    pull: "左右两组同时进 → 能量组合 + 火花传递人 → 约 4.5 分钟",
    assignTpl: [
      "【左组】{mt}+{h2}+半数 DPS",
      "【右组】{ot}+{h1}+半数 DPS",
      "【弹性】有 {t3}/{h3} 时：左右尽量各 1 坦 1 奶；多出的 {t3}/{h3} 补较弱一侧",
      "【开箱】遗物优先；推荐少火花组合",
      "【火花】10 秒内跨组传递；指定倒计时喊话",
      "【机制】物质扰乱上石柱；炸弹丢角；女皇之怒驱散",
    ],
    cdEvents: [
      { when: "火花将爆（失误）", prefer: ["shell", "tide", "kings", "rally", "aura"] },
    ],
  },
  {
    id: "thok",
    idx: 11,
    name: "嗜血的索克",
    lust: "开场",
    flex: { heal: true },
    pull: "监狱绿→蓝→红 + 致死再吃 → 啸次数专人 → 嗜血开场",
    assignTpl: [
      "【P1】{mt} 主抗（正面/尾部留空）；{ot} 换坦；三角站位吃啸（勿全叠一点）",
      "【转阶】约加速 20～23 层集合进 P2，勿过 30",
      "【奶】{h1} 冷却用满；{h2} 顶啸链；毒阶段蝙蝠预留减抬",
      "【弹性奶】有 {h3} 时：啸链优先 {h3} 链接 + 虔诚专注；潮汐穿插抬血",
      "【P2】开监绿→蓝→红；狱卒致死后再吃；P2→P1 上降治疗砍回血",
      "【锁定】风筝勿扫团；【计数】专人报啸次数",
      "【软狂暴】第4次P2无监风筝；啸#31前击杀",
    ],
    cdEvents: [
      { when: "啸链（越来越密）", prefer: ["aura", "link", "barrier", "demo", "shell", "tide", "rally"], note: "虔诚可减打断" },
      { when: "火阶段", prefer: ["barrier", "aura", "kings", "rally"] },
    ],
  },
  {
    id: "blackfuse",
    idx: 12,
    name: "攻城匠师黑索",
    lust: "开场",
    flex: { tank: true },
    pull: "上带名单 + 波次表 → 伐木机35码 → 约12%停带",
    assignTpl: [
      "【坦】{mt}/{ot} 各拉伐木机约 35 码；叠静电",
      "【弹性坦】有 {t3} 时：{t3} 接电磁/协助风筝，双伐木仍 {mt}/{ot}",
      "【上带】近战/灵活DPS轮班；对照波次表只打指定件",
      "【波次】多数打地雷；3/11打飞弹；6打一个地雷；电磁波加人手",
      "【锯刃】躲或 {trap}/隐身/鬼影可不出锯；中火线禁假死脱战（会转火）",
      "【地雷】落地减速控场；工程腰带群晕好用",
      "【12%】停带烧 Boss",
    ],
    cdEvents: [
      { when: "电磁波", prefer: ["shell", "tide", "kings"] },
      { when: "矩阵触发（难救）", prefer: ["barrier", "aura", "rally", "hymn"] },
    ],
  },
  {
    id: "paragons",
    idx: 13,
    name: "卡拉克西英杰",
    lust: "夏克里尔窗口",
    pull: "九人击杀序 + 瞄准/琥珀/彩毒 → EAB 即报",
    assignTpl: [
      "【集火】死跟击杀序；{mt}/{ot} 换拉当前目标",
      "【瞄准】听指挥分摊；【琥珀】按表破控",
      "【寄生】蝎吃虫；【彩毒/火刃】按颜色/出线",
      "【收割】点名外置；【EAB】捡到即报",
    ],
    cdEvents: [
      { when: "瞄准分摊后", prefer: ["shell", "tide", "kings"] },
      { when: "收割点名", prefer: ["ps", "sac", "ironbark", "cocoon"] },
      { when: "夏克里尔爆发", prefer: ["barrier", "aura"], note: "嗜血同步" },
    ],
  },
  {
    id: "garrosh",
    idx: 14,
    name: "加尔鲁什·地狱咆哮",
    lust: "约 10% 进 P3",
    flex: { heal: true },
    pull: "能量<25进间奏 + 西工程师优先 → P4铁星打断分工",
    assignTpl: [
      "【P1】{mt} 主抗；出亵渎；西工程师优先；铁星勿撞团",
      "【间奏】第一次能量必须 <25（理想<21）",
      "【P2】解心控；旋风出；绝望约3层换坦",
      "【强化】小怪约8码分散死",
      "【P4】恶意分摊；专人看能量；铁星打断暴怒具现",
      "【奶】{h1} 盯坦绝望窗；{h2} 团血/分摊后抬",
      "【弹性奶】有 {h3} 时：恶意分摊/强化炸用链接潮汐；{h1}/{h2} 保坦",
    ],
    cdEvents: [
      { when: "恶意分摊", prefer: ["shell", "tide", "kings"] },
      { when: "绝望层数危急", prefer: ["ps", "sac"] },
      { when: "强化小怪炸", prefer: ["barrier", "aura", "rally"] },
      { when: "暴怒具现漏断", prefer: ["barrier", "aura", "link", "rally", "hymn"], note: "通常难救" },
    ],
  },
];
